<?php

namespace App\Repository;

/**
 * LinkUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkUserRepository extends \Doctrine\ORM\EntityRepository
{
}
