web:
  image: virtuasa/php:7.2
  ports: 
    - "8080:80"
    - "8443:443"
  volumes: 
    - ./:/data

# Build:    `docker-compose build`
# Run:      `docker-compose up -d`
# Stop:     `docker-compose down`
# Shell:    `docker-compose exec web /bin/bash`

# Windows:  `docker-compose run web bash -c 'dos2unix scripts/*.sh && chmod +x scripts/*.sh'`

# doctrine: `docker-compose run web ./scripts/doctrine.sh`
# phpcs:    `docker-compose run web ./scripts/phpcs.sh`
# phpcbf:   `docker-compose run web ./scripts/phpcbf.sh`
# phpunit:  `docker-compose run web ./scripts/phpunit.sh`