# This file is part of GL YAUSS.
# See: <https://github.com/golflima/yauss>.
#
# Copyright (C) 2017 Jérémy Walther <jeremy.walther@golflima.net>.
#
# For the full copyright and license information, please view
# the COPYRIGHT file that was distributed with this source code.
# Otherwise, see: <https://www.gnu.org/licenses/agpl-3.0>.

App\Entity\AuthToken:
    type: entity
    name: yauss_auth_tokens
    repositoryClass: App\Repository\AuthTokenRepository
    id:
        id:
            type: string
            length: 128
            generator: { strategy: NONE }
            options:
                comment: Token, used for user authentification.
    fields:
        expire:
            type: datetime
            nullable: true
            options:
                comment: Expiration date of the token. It won't expire it set to NULL.
    manyToOne:
        user:
            targetEntity: User
            inversedBy: authTokens