# This file is part of GL YAUSS.
# See: <https://github.com/golflima/yauss>.
#
# Copyright (C) 2017 Jérémy Walther <jeremy.walther@golflima.net>.
#
# For the full copyright and license information, please view
# the COPYRIGHT file that was distributed with this source code.
# Otherwise, see: <https://www.gnu.org/licenses/agpl-3.0>.

App\Entity\GroupAcl:
    type: entity
    name: yauss_groups_acl
    repositoryClass: App\Repository\GroupAclRepository
    id:
        group:
            associationKey: true
    fields:
        ace:
            type: string
            length: 16 # <EntityName>_Owner, <EntityName>_Admin, <EntityName>_Write, <EntityName>_Read
    manyToOne:
        group:
            targetEntity: Group
            inversedBy: acl