# This file is part of GL YAUSS.
# See: <https://github.com/golflima/yauss>.
#
# Copyright (C) 2017 Jérémy Walther <jeremy.walther@golflima.net>.
#
# For the full copyright and license information, please view
# the COPYRIGHT file that was distributed with this source code.
# Otherwise, see: <https://www.gnu.org/licenses/agpl-3.0>.

App\Entity\Group:
    type: entity
    name: yauss_groups
    repositoryClass: App\Repository\GroupRepository
    indexes:
        name_index:
            columns: [ name ]
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
            unique: true
    oneToMany:
        acl:
            targetEntity: GroupAcl
            mappedBy: group
    manyToOne:
        users:
            targetEntity: User
            mappedBy: group