# This file is part of GL YAUSS.
# See: <https://github.com/golflima/yauss>.
#
# Copyright (C) 2017 Jérémy Walther <jeremy.walther@golflima.net>.
#
# For the full copyright and license information, please view
# the COPYRIGHT file that was distributed with this source code.
# Otherwise, see: <https://www.gnu.org/licenses/agpl-3.0>.

App\Entity\UserGroup:
    type: entity
    name: yauss_user_groups
    repositoryClass: App\Repository\UserGroupRepository
    indexes:
        name_index:
            columns: [ name ]
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
            unique: true
        allow:
            type: string
            length: 255
        deny:
            type: string
            length: 255
    oneToMany:
        childs:
            targetEntity: UserGroup
            mappedBy: parent
    manyToOne:
        parent:
            targetEntity: UserGroup
            mappedBy: childs
    manyToMany:
        users:
            targetEntity: User
            mappedBy: groups